{{- if .Values.tenants.enabled }}
{{- range $tenantName, $tenant := .Values.tenants }}
{{- if ne $tenantName "enabled" }}
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: {{ $tenant.cudn }}
  labels:
    infra.aclab.uk/advertise: "true"
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
{{- range $tenant.namespaces }}
          - {{ . }}
{{- end }}
  network:
    layer2:     # layer2 | layer3 | localnet | see oc explain ClusterUserDefinedNetwork.spec.network localnet is L2 but to physical external network, only supported with secondaries
      ipam:
        lifecycle: Persistent
        # mode: Enabled           #     Enabled | Disabled | disabled only works for secondaries and will assign mac not ip address
      role: Primary
      subnets:
{{- range $tenant.subnets }}
        - {{ . }}
{{- end }}
    topology: Layer2
---
{{- end }}
{{- end }}
{{- end }}