## referenced from https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/installing_on_vmware_vsphere/installation-config-parameters-vsphere
apiVersion: v1
baseDomain: aclab.uk
metadata:
  name: home-ocp01
platform:
  vsphere:
    apiVIPs:
    - 10.166.109.1    # kubeapi vip backed by keepalived
    ingressVIPs:
    - 10.166.109.2    # haproxy vip backed by keepalived
    diskType: thin
    vcenters:
      - server: vc01.aclab.uk
        user: administrator@vsphere.local
        password: somethingsecure
        datacenters: 
         - home-m01-dc01
    failureDomains:   
      - name: home-fd-01
        zone: home-zone-01
        region: home
        server: vc01.aclab.uk
        topology:
          datacenter: home-m01-dc01
          datastore: /home-m01-dc01/datastore/home-m01-cl01-ds-vsan01
          computeCluster: /home-m01-dc01/host/home-m01-cl01
          folder: /home-m01-dc01/vm/Infra/OpenShift
          networks:
            - dp-ocp-mgmt-v109
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14       # non-routable for for cluster, default cidr pasted for information only
    hostPrefix: 23            # default prefix allocation per node, pasted for information only
  serviceNetwork:
  - 172.30.0.0/16             # non-routable for services, default cidr pasted for information only
  machineNetwork:
  - cidr: 10.166.109.0/24        # host network where the nodes will reside, this matches the vmware dp-port group you assign the virtual machines to
  ovnKubernetesConfig:
    ipv4:
      internalJoinSubnet: 100.64.0.0/16   # default internal join subnet pasted for information only
pullSecret: 'changeme
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbrOX9HZdwLNHl1vgSvSdfGTXDP2ygof7UXYqsV6cSm home-ocp01'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIE8jCCA1qgAwIBAgIJAPNfQmsd3FOrMA0GCSqGSIb3DQEBCwUAMIGUMQswCQYD
  VQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZ
  FgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
  BAoMDXZjMDEuYWNsYWIudWsxGzAZBgNVBAsMElZNd2FyZSBFbmdpbmVlcmluZzAe
  Fw0yNjAyMDgwNzUyNDNaFw0zNjAyMDYwNzUyNDNaMIGUMQswCQYDVQQDDAJDQTEX
  MBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDEL
  MAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAoMDXZjMDEu
  YWNsYWIudWsxGzAZBgNVBAsMElZNd2FyZSBFbmdpbmVlcmluZzCCAaIwDQYJKoZI
  hvcNAQEBBQADggGPADCCAYoCggGBALr6kU+VfSwwFezTWQVtThAiHN37qlkfbPD2
  lynbpeQyAAVPYHa5is30ymNlNAX5eN53Q4jHNGosEfqa0g+pXYZ4OoUy1bztkXPe
  nE9kPOxEDkTOkyOIsJ0U1xf319KS9wbLY18doGydnCBimyIyKXqgf/Cy9TIG3ttL
  m/zmaczx4TYpok7xI/iniLbxda4/DC/TqM4chTqLQmoRATwQVyF6WEAXDsHZy4Wq
  t/IQ2fZ5JIaBkK7AgpcF2giSPvggjrVoTONd3MYgEJpKmN9jtlqnFIVu4Utx+CLb
  Zrc90ZYX8kQki3ji+OUVGuSM+GloRV8aEWAaV+iFAI3pz9EVWzQ1Tg0OilPbEJOo
  v/+Fo0cqAEiXc8F6G14ogxk8xDcVoecFOBkjysBfnILm251PO5h1r0lJWTWZIQUQ
  mx4+7f9KWbjY1xQ0Ba8pUJ5j2jAH+qyLpFbItIjvkOo6O7bXhi4M5HRYTLewiG2D
  jVf3LSOwdjuknr2rjpYAIG10Z6lWpQIDAQABo0UwQzAdBgNVHQ4EFgQUc2r2MIrX
  rLD9kzXSX2zZPXGiKrwwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
  AQAwDQYJKoZIhvcNAQELBQADggGBAJTHN3Ku4C4SKTjc6PPXibDzelYoAQj9lFjM
  Tb1R3uHvZznId6pJc/G8aNg+itczq5DTuEuvwhaIqXoC/f4FFMbj6iWuzJVlwa5E
  xL1kBN92R3fio1LkUsW1+UcTpu6JdKRD4t/9UbtH04rLRsaWY2wNoYDQwmYHuLYP
  +8n9olfzKElOhnNp9zyZ7fVfVzij9O5YrnzwGvqlS5YK76nHXbTTUsC+IKPEBMZU
  +8KDWiZBRZ1BcaKlyKKYiCiwrrDcxOLog1/I/RNCTNXAyXJOP8bZ9IlewC17w8ST
  2a0uL4KpkcClj7s1DjNIFGRHrq7kml6OBV3iwVIPnOQwW9GyWfSPQMqrhVz6Nezg
  x8iVxtbT8aLQONSe7Xjfck7B8yvCskD9HZ66yGW1g1hqvAV/3i3ybhtaf6KIaXP0
  vLr545r0OkjtzYotlH7OFY3LMCt+lQBgN2Lj0U6waLTiDCV7iEetN2V9It9X+Pzp
  heCvmGZVwNw864mogT+Gbh8wHGcEBg==
  -----END CERTIFICATE-----